### ISSUE TITLE
Computational requirements of HIPPO greedy algorithm

### ISSUE THREAD

**Issue by lely475** [kaczmarj/HIPPO#3]
Hi Jakub,

Thank you for sharing this very interesting work. I would be interested to know how computationally expensive it is to run the HIPPO greedy algorithm on a WSI with N tiles.  And what hardware was required for what time frame? How does this scale with an increase in tiles?

Thank you already!
Lydia

**Comment by kaczmarj** [comment]
hi @lely475 - thanks for reaching out. the greedy search algorithm is approximately O(n^2).

i used an nvidia A100 and i set `torch.set_float32_matmul_precision("high")` to increase the speed. it can take several hours to run a slide with a few thousand patches. what i do in practice is run it on 5% of the patches, to find the most important 5% patches.

i am alo working on a version where K patches are removed at each iteration. that will greatly decrease the running time.

**Comment by kaczmarj** [comment]
i am closing this issue. please re-open if you wish.
